apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-service-deployment
  labels:
    app: twitter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-service
  template:
    metadata:
      labels:
        app: twitter-service
    spec:
      containers:
      - name: twitter-service
        image: williammcenery/twitter-service-rest-proxy
        ports:
          - containerPort: 5000
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: twitter-service-secret
              key: twitter_api_token
        - name: KAFKA_REST_PROXY_URL
          valueFrom:
            configMapKeyRef:
              name: twitter-service-configmap
              key: kafka_rest_proxy_url
        - name: CONSUMER_TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: twitter-service-configmap
              key: consumer_topic_name
        - name: PRODUCER_TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: twitter-service-configmap
              key: producer_topic_name
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-service
spec:
  selector:
    app: twitter-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000